// Skill Card Synchronization
// Auto-syncs skill card markdown files from filesystem to database
// These act as persistent system settings that are version-controlled

import { PrismaClient } from '@prisma/client'

// Dynamic import to prevent fs from being bundled into client-side code
const getFs = async () => {
  const fs = await import('fs')
  const path = await import('path')
  return { readFileSync: fs.readFileSync, join: path.join }
}

const SKILL_CARDS = [
  {
    filename: 'skill_tracker_reading.md',
    title: 'skill_tracker_reading',
    tags: ['skill', 'tracker', 'reading', 'spreadsheet'],
  },
  {
    filename: 'skill_performance_benchmarks.md',
    title: 'skill_performance_benchmarks',
    tags: ['skill', 'performance', 'benchmarks', 'metrics'],
  },
  {
    filename: 'skill_campaign_strategy.md',
    title: 'skill_campaign_strategy',
    tags: ['skill', 'campaign', 'strategy', 'planning'],
  },
  {
    filename: 'skill_legal_compliance.md',
    title: 'skill_legal_compliance',
    tags: ['skill', 'legal', 'compliance', 'contracts'],
  },
  {
    filename: 'skill_negotiation.md',
    title: 'skill_negotiation',
    tags: ['skill', 'negotiation', 'deals', 'rates', 'sow'],
  },
]

/**
 * Sync skill card files from filesystem to database
 * Call this on app startup or after updating skill card files
 */
export async function syncSkillCards(brandId: string, prisma: PrismaClient): Promise<{
  synced: number
  errors: string[]
}> {
  const { readFileSync, join } = await getFs()
  const skillsPath = join(process.cwd(), 'src', 'lib', 'skills')
  let synced = 0
  const errors: string[] = []

  console.log('[Skill Cards] Syncing to database...')

  // Ensure Industry Knowledge folder exists
  let industryFolder = await prisma.knowledgeFolder.findFirst({
    where: {
      brandId,
      name: 'Industry Knowledge',
      folderType: 'system',
    },
  })

  if (!industryFolder) {
    industryFolder = await prisma.knowledgeFolder.create({
      data: {
        brandId,
        name: 'Industry Knowledge',
        icon: 'book-open',
        folderType: 'system',
        orderIndex: 5,
      },
    })
    console.log('[Skill Cards] Created Industry Knowledge folder')
  }

  // Sync each skill card
  for (const skill of SKILL_CARDS) {
    try {
      const filePath = join(skillsPath, skill.filename)
      const content = readFileSync(filePath, 'utf-8')

      // Check if skill card already exists
      const existing = await prisma.knowledgeDocument.findFirst({
        where: {
          brandId,
          folderId: industryFolder.id,
          title: skill.title,
        },
      })

      if (existing) {
        // Update existing
        await prisma.knowledgeDocument.update({
          where: { id: existing.id },
          data: {
            content,
            tags: JSON.stringify(skill.tags),
            isAutoGenerated: true, // Mark as system-managed
          },
        })
        console.log(`[Skill Cards] Updated: ${skill.title}`)
      } else {
        // Create new
        await prisma.knowledgeDocument.create({
          data: {
            brandId,
            folderId: industryFolder.id,
            title: skill.title,
            content,
            documentType: 'manual',
            icon: 'book-open',
            isAutoGenerated: true, // Mark as system-managed
            tags: JSON.stringify(skill.tags),
            orderIndex: 0,
          },
        })
        console.log(`[Skill Cards] Created: ${skill.title}`)
      }

      synced++
    } catch (error) {
      const errorMsg = `Failed to sync ${skill.filename}: ${error}`
      console.error(`[Skill Cards] ${errorMsg}`)
      errors.push(errorMsg)
    }
  }

  console.log(`[Skill Cards] Sync complete: ${synced}/${SKILL_CARDS.length} synced`)

  return { synced, errors }
}

/**
 * Sync skill cards for all brands
 * Useful for initial setup or after system updates
 */
export async function syncSkillCardsForAllBrands(prisma: PrismaClient): Promise<void> {
  const brands = await prisma.brand.findMany({
    select: { id: true, name: true },
  })

  console.log(`[Skill Cards] Syncing for ${brands.length} brand(s)...`)

  for (const brand of brands) {
    try {
      await syncSkillCards(brand.id, prisma)
    } catch (error) {
      console.error(`[Skill Cards] Failed to sync for brand ${brand.name}:`, error)
    }
  }

  console.log('[Skill Cards] Global sync complete')
}
