'use client'

import { useState } from 'react'
import {
  ChevronRight,
  ChevronDown,
  Folder,
  FolderOpen,
  FileText,
  Users,
  Lightbulb,
  TrendingUp,
  MessageSquare,
  Plus,
  Star,
  AlertTriangle,
  Layers,
  BarChart,
  Palette,
  Calendar,
  DollarSign,
  Book,
  Clipboard,
  CheckCircle,
  Upload,
} from 'lucide-react'
import { cn } from '@/lib/utils'

interface DocumentNode {
  id: string
  title: string
  icon: string | null
  documentType: string
  isAutoGenerated: boolean
}

interface FolderNode {
  id: string
  name: string
  icon: string | null
  folderType: string
  children: FolderNode[]
  documents: DocumentNode[]
}

interface KnowledgeTreeNavProps {
  folders: FolderNode[]
  selectedDocId: string | null
  onSelectDoc: (docId: string) => void
  onCreateFolder: () => void
  onCreateDocument: () => void
  onUploadFile: () => void
}

const iconMap: Record<string, any> = {
  users: Users,
  lightbulb: Lightbulb,
  'trending-up': TrendingUp,
  'message-square': MessageSquare,
  'file-text': FileText,
  'file-pdf': FileText,
  star: Star,
  'alert-triangle': AlertTriangle,
  layers: Layers,
  'bar-chart': BarChart,
  palette: Palette,
  calendar: Calendar,
  'dollar-sign': DollarSign,
  book: Book,
  clipboard: Clipboard,
  'check-circle': CheckCircle,
  folder: Folder,
  'book-open': Book,
}

export default function KnowledgeTreeNav({
  folders,
  selectedDocId,
  onSelectDoc,
  onCreateFolder,
  onCreateDocument,
  onUploadFile,
}: KnowledgeTreeNavProps) {
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(
    new Set(folders.map((f) => f.id)) // Expand root folders by default
  )

  const toggleFolder = (folderId: string) => {
    setExpandedFolders((prev) => {
      const next = new Set(prev)
      if (next.has(folderId)) {
        next.delete(folderId)
      } else {
        next.add(folderId)
      }
      return next
    })
  }

  const getIcon = (iconName: string | null) => {
    return iconMap[iconName || 'folder'] || Folder
  }

  const renderDocument = (doc: DocumentNode, level: number) => {
    const isSelected = selectedDocId === doc.id
    const Icon = getIcon(doc.icon)

    return (
      <div
        key={doc.id}
        className={cn(
          'flex items-center gap-2 px-3 py-2 cursor-pointer rounded-md transition-colors',
          isSelected
            ? 'bg-orange-50 border border-orange-300'
            : 'hover:bg-stone-50'
        )}
        style={{ paddingLeft: `${(level + 1) * 16 + 12}px` }}
        onClick={() => onSelectDoc(doc.id)}
      >
        <Icon
          className={cn(
            'h-4 w-4 flex-shrink-0',
            isSelected ? 'text-orange-600' : 'text-stone-500'
          )}
        />
        <span
          className={cn(
            'text-sm truncate',
            isSelected ? 'text-orange-900 font-medium' : 'text-stone-700'
          )}
        >
          {doc.title}
        </span>
        {doc.isAutoGenerated && (
          <span className="text-[10px] text-blue-600 bg-blue-50 px-1.5 py-0.5 rounded ml-auto flex-shrink-0">
            Auto
          </span>
        )}
      </div>
    )
  }

  const renderFolder = (folder: FolderNode, level: number = 0) => {
    const isExpanded = expandedFolders.has(folder.id)
    const Icon = getIcon(folder.icon)
    const hasContent =
      folder.documents.length > 0 || folder.children.length > 0

    return (
      <div key={folder.id}>
        {/* Folder Header */}
        <div
          className={cn(
            'flex items-center gap-2 px-3 py-2 cursor-pointer hover:bg-stone-50 rounded-md transition-colors'
          )}
          style={{ paddingLeft: `${level * 16 + 12}px` }}
          onClick={() => toggleFolder(folder.id)}
        >
          {hasContent ? (
            isExpanded ? (
              <ChevronDown className="h-4 w-4 text-stone-400 flex-shrink-0" />
            ) : (
              <ChevronRight className="h-4 w-4 text-stone-400 flex-shrink-0" />
            )
          ) : (
            <span className="w-4 flex-shrink-0" />
          )}
          {isExpanded ? (
            <FolderOpen className="h-4 w-4 text-amber-500 flex-shrink-0" />
          ) : (
            <Icon className="h-4 w-4 text-stone-600 flex-shrink-0" />
          )}
          <span className="text-sm font-medium text-stone-900 truncate">
            {folder.name}
          </span>
          {folder.folderType === 'system' && (
            <span className="text-[10px] text-stone-400 ml-auto flex-shrink-0">
              {folder.documents.length > 0 && `${folder.documents.length}`}
            </span>
          )}
        </div>

        {/* Expanded Content */}
        {isExpanded && (
          <div>
            {/* Documents first */}
            {folder.documents.map((doc) => renderDocument(doc, level + 1))}

            {/* Child Folders */}
            {folder.children.map((child) => renderFolder(child, level + 1))}
          </div>
        )}
      </div>
    )
  }

  return (
    <div className="h-full flex flex-col bg-white border-r border-stone-200 overflow-hidden">
      {/* Header */}
      <div className="p-4 border-b border-stone-200 flex-shrink-0">
        <h2 className="text-lg font-semibold text-stone-900">Knowledge Base</h2>
        <p className="text-xs text-stone-500 mt-1">
          Organized learnings & insights
        </p>
        <div className="flex flex-col gap-2 mt-3">
          <button
            onClick={onUploadFile}
            className="w-full flex items-center justify-center gap-1.5 px-3 py-2 text-sm bg-orange-500 hover:bg-orange-600 text-white rounded-md transition-colors font-medium"
          >
            <Upload className="h-4 w-4" />
            Upload Document
          </button>
          <div className="flex gap-2">
            <button
              onClick={onCreateFolder}
              className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 text-xs bg-stone-100 hover:bg-stone-200 text-stone-700 rounded-md transition-colors"
            >
              <Plus className="h-3 w-3" />
              Folder
            </button>
            <button
              onClick={onCreateDocument}
              className="flex-1 flex items-center justify-center gap-1 px-3 py-1.5 text-xs bg-stone-100 hover:bg-stone-200 text-stone-700 rounded-md transition-colors"
            >
              <Plus className="h-3 w-3" />
              Note
            </button>
          </div>
        </div>
      </div>

      {/* Tree */}
      <div className="flex-1 overflow-y-auto p-2">
        {folders.length === 0 ? (
          <div className="p-4 text-center text-stone-500 text-sm">
            <p>No knowledge structure yet.</p>
            <p className="mt-1 text-xs">Sync a campaign tracker to generate.</p>
          </div>
        ) : (
          folders.map((folder) => renderFolder(folder))
        )}
      </div>
    </div>
  )
}
