import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import { syncSkillCardsForAllBrands } from '@/lib/sync-skill-cards'

/**
 * POST /api/skills/sync
 * Sync skill card markdown files from codebase to database
 * Call this after updating skill card .md files
 */
export async function POST() {
  try {
    console.log('[API] Syncing skill cards...')

    await syncSkillCardsForAllBrands(prisma)

    return NextResponse.json({
      success: true,
      message: 'Skill cards synced successfully',
    })
  } catch (error) {
    console.error('[API] Skill card sync error:', error)

    return NextResponse.json(
      {
        success: false,
        error: error instanceof Error ? error.message : 'Failed to sync skill cards',
      },
      { status: 500 }
    )
  }
}

/**
 * GET /api/skills/sync
 * Returns status of skill cards
 */
export async function GET() {
  try {
    const brands = await prisma.brand.findMany({
      select: { id: true, name: true },
    })

    const skillCardCounts = await Promise.all(
      brands.map(async (brand) => {
        const count = await prisma.knowledgeDocument.count({
          where: {
            brandId: brand.id,
            isAutoGenerated: true,
            OR: [
              { title: { contains: 'skill_tracker_reading' } },
              { title: { contains: 'skill_performance_benchmarks' } },
              { title: { contains: 'skill_campaign_strategy' } },
              { title: { contains: 'skill_legal_compliance' } },
              { title: { contains: 'skill_negotiation' } },
            ],
          },
        })

        return {
          brandId: brand.id,
          brandName: brand.name,
          skillCardsCount: count,
        }
      })
    )

    return NextResponse.json({
      brands: skillCardCounts,
      expectedPerBrand: 5,
    })
  } catch (error) {
    console.error('[API] Skill card status error:', error)

    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to get skill card status',
      },
      { status: 500 }
    )
  }
}
