import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import {
  getDocumentWithData,
  updateDocument,
  deleteDocument,
} from '@/lib/knowledge-generator'

// GET /api/brands/[id]/knowledge/documents/[docId] - Get document with resolved data
export async function GET(
  request: Request,
  { params }: { params: { id: string; docId: string } }
) {
  try {
    const document = await getDocumentWithData(params.docId, prisma)

    if (!document) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    // Verify document belongs to this brand
    if (document.brandId !== params.id) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    return NextResponse.json(document)
  } catch (error) {
    console.error('Failed to fetch document:', error)
    return NextResponse.json(
      { error: 'Failed to fetch document' },
      { status: 500 }
    )
  }
}

// PUT /api/brands/[id]/knowledge/documents/[docId] - Update document
export async function PUT(
  request: Request,
  { params }: { params: { id: string; docId: string } }
) {
  try {
    const body = await request.json()
    const { title, content, tags } = body

    // Check if document exists and is editable
    const existing = await prisma.knowledgeDocument.findUnique({
      where: { id: params.docId },
    })

    if (!existing) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    if (existing.brandId !== params.id) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    if (existing.isAutoGenerated) {
      return NextResponse.json(
        { error: 'Cannot edit auto-generated documents' },
        { status: 403 }
      )
    }

    const updates: { title?: string; content?: string; tags?: string } = {}
    if (title !== undefined) updates.title = title
    if (content !== undefined) updates.content = content
    if (tags !== undefined) updates.tags = tags

    const updated = await updateDocument(params.docId, updates, prisma)

    return NextResponse.json(updated)
  } catch (error) {
    console.error('Failed to update document:', error)
    return NextResponse.json(
      { error: 'Failed to update document' },
      { status: 500 }
    )
  }
}

// DELETE /api/brands/[id]/knowledge/documents/[docId] - Delete document
export async function DELETE(
  request: Request,
  { params }: { params: { id: string; docId: string } }
) {
  try {
    // Check if document exists
    const existing = await prisma.knowledgeDocument.findUnique({
      where: { id: params.docId },
    })

    if (!existing) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    if (existing.brandId !== params.id) {
      return NextResponse.json({ error: 'Document not found' }, { status: 404 })
    }

    const deleted = await deleteDocument(params.docId, prisma)

    if (!deleted) {
      return NextResponse.json(
        { error: 'Cannot delete auto-generated documents' },
        { status: 403 }
      )
    }

    return NextResponse.json({ success: true })
  } catch (error) {
    console.error('Failed to delete document:', error)
    return NextResponse.json(
      { error: 'Failed to delete document' },
      { status: 500 }
    )
  }
}
