import { NextResponse } from 'next/server'
import { prisma } from '@/lib/db'
import {
  generateKnowledgeStructure,
  createCustomFolder,
  createCustomDocument,
} from '@/lib/knowledge-generator'

// GET /api/brands/[id]/knowledge - Get folder tree structure
export async function GET(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const brandId = params.id

    // Check if brand exists
    const brand = await prisma.brand.findUnique({
      where: { id: brandId },
      select: { id: true, name: true },
    })

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 })
    }

    // Get all folders with their documents and children
    const folders = await prisma.knowledgeFolder.findMany({
      where: { brandId, parentId: null }, // Root folders only
      include: {
        documents: {
          orderBy: { orderIndex: 'asc' },
        },
        children: {
          include: {
            documents: {
              orderBy: { orderIndex: 'asc' },
            },
            children: {
              include: {
                documents: {
                  orderBy: { orderIndex: 'asc' },
                },
              },
              orderBy: { orderIndex: 'asc' },
            },
          },
          orderBy: { orderIndex: 'asc' },
        },
      },
      orderBy: { orderIndex: 'asc' },
    })

    // Get stats
    const stats = {
      totalFolders: await prisma.knowledgeFolder.count({ where: { brandId } }),
      totalDocuments: await prisma.knowledgeDocument.count({
        where: { brandId },
      }),
      autoGeneratedDocs: await prisma.knowledgeDocument.count({
        where: { brandId, isAutoGenerated: true },
      }),
    }

    return NextResponse.json({ folders, stats })
  } catch (error) {
    console.error('Failed to fetch knowledge structure:', error)
    return NextResponse.json(
      { error: 'Failed to fetch knowledge' },
      { status: 500 }
    )
  }
}

// POST /api/brands/[id]/knowledge - Create custom folder or document, or regenerate structure
export async function POST(
  request: Request,
  { params }: { params: { id: string } }
) {
  try {
    const brandId = params.id
    const body = await request.json()
    const { action, name, parentId, title, content, folderId } = body

    // Check if brand exists
    const brand = await prisma.brand.findUnique({
      where: { id: brandId },
      select: { id: true },
    })

    if (!brand) {
      return NextResponse.json({ error: 'Brand not found' }, { status: 404 })
    }

    switch (action) {
      case 'generate':
        // Generate or regenerate the knowledge structure
        const result = await generateKnowledgeStructure(brandId, prisma)
        return NextResponse.json({
          success: true,
          message: `Created ${result.foldersCreated} folders and ${result.documentsCreated} documents`,
          ...result,
        })

      case 'createFolder':
        if (!name) {
          return NextResponse.json(
            { error: 'Folder name is required' },
            { status: 400 }
          )
        }
        const folder = await createCustomFolder(
          brandId,
          name,
          parentId || null,
          prisma
        )
        return NextResponse.json(folder)

      case 'createDocument':
        if (!title) {
          return NextResponse.json(
            { error: 'Document title is required' },
            { status: 400 }
          )
        }
        const document = await createCustomDocument(
          brandId,
          folderId || null,
          title,
          content || '',
          prisma
        )
        return NextResponse.json(document)

      default:
        return NextResponse.json(
          { error: 'Invalid action. Use: generate, createFolder, createDocument' },
          { status: 400 }
        )
    }
  } catch (error) {
    console.error('Failed to process knowledge request:', error)
    return NextResponse.json(
      { error: 'Failed to process request' },
      { status: 500 }
    )
  }
}
